### PR TITLE
Boot splash animation

### PR DESCRIPTION
**Pull request by mym0404**
**This PR is based on #128.** For merging this PR, #128 has to be merged first.

## Description

I created a simple splash screen and animation(pulse in `Android`, shared element in `Android`, and `iOS` both).

# Android

android

In this process, I created an `Android Native Module`.
Basically, splash screen logic depends on `react-native-bootsplash` in iOS. But, the original purpose of the `react-native-bootsplash` library is to make your simple logo animatable in splash screen instead of whole background image like splash screen.

So I created a simple `Android Native Module` for that. This module is considered from `react-native-bootsplash` android code. The followings are the list of files related to the native module.

image

_view_splash.xml_
image

Also, I updated the android manifest file for `Activity` transition behavior.
`SplashActivity` is launched as main(using intent-filter) and it would launch `MainActivity`.
The splash screen is a combination of gradient XML background and layout XML file. 

I also added a simple pulse animation to image logo with Android `ObjectAnimator`

# iOS

ios

I didn't any work in XCode except fix usage of `react-native-bootsplash` to follow that's a guideline on the homepage.

# RN

* Remove any logic related to splash in `App.tsx`
* Update `mobile.tsx`(Sign In) for shared element transition animation when the splash screen is hiding. It is a simple and ugly code(hardcoded position). But it looks like working well..?
* Unrelated automatic linting in some files - sorry to that.

## Related Issues

In `Android`, the layout view will be added to `decorView` in the android view hierarchy. The `BootSplash` java class contains `root` as a static field so Android studio warns about that(inhibiting static `Context`). But containing **Application Context** is not problematic in android I think.

## Tests

I didn't add any test codes.
But add `react-native-bootsplash` global node module mock in `__mocks__` directory for preventing break testings.

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk-mobile/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn lint && yarn tsc`
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by mym0404** [comment]
I will add splash screen color cheme change on whether device is set with dark mode.

**Comment by hyochan** [comment]
> I will add splash screen color cheme change on whether device is set with dark mode.

Ok. I'll hold this for review until you think you are done.

**Comment by hyochan** [comment]
@YongPilMoon Hey looks like there is another volunteer on your consideration. Would you like to look into this and work together?

**Comment by hyochan** [comment]
Having jest issue which is [related](https://github.com/software-mansion/react-native-reanimated/issues/426)

**Comment by mym0404** [comment]
@hyochan I think this is because mocking `TouchableOpacity` in `jestSetup.js`

image

**Pull request merged**
