### PR TITLE
[WIP] migration: react navigation v5

### PR DESCRIPTION
**Pull request by hyochan**
## Description

react-navigation@next package which is currently `v5` has majority updates which make the code looks very pretty and concise.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide](https://github.com/dooboolab/hackatalk-mobile/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [x] Run `yarn lint`
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
@marsinearth Please check this! I've got this first hand.

**Comment by Ta2Rim** [comment]
Question: Is SwitchNavigator is deprecated?
Migrating my project to react-navigation-v5, I convert react-navigation/switchNavigator to @react-navigation/compat/switchNavigator following migration. [docs](https://reactnavigation.org/docs/en/next/compatibility.html)

But you converted switchNavigator to RootNavigator that you made with StackNavigator
So I wondered switchNavigator is deprecated

**Comment by hyochan** [comment]
Thanks for the detail. Looks like I've missed this in the `doc` and thanks for the update 👍 

Would you give us an effort to add `SwitchNavigator` in `hackatalk`?

**Comment by Ta2Rim** [comment]
@hyochan I'd love to

**Comment by Ta2Rim** [comment]
How can I work on it? 
I don’t know what branch I have to checkout

**Comment by hyochan** [comment]
@Ta2Rim PR is available on master branch. You can refer to the [clip](https://m.youtube.com/watch?v=2IWd37BHnkg&t=557s)

**Comment by Ta2Rim** [comment]
@hyochan 
I tried, but it doesn't work with these errors.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, 
but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method,
    in SceneView (at TabView.tsx:165)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Pager.tsx:667)
    in PanGestureHandler (at Pager.tsx:659)
    in Pager (at TabView.tsx:126)
    in RCTView (at View.js:45)
    in View (at TabView.tsx:125)
    in TabView (at MaterialTopTabView.tsx:152)
    in MaterialTopTabView (at createMaterialTopTabNavigator.tsx:43)
    in MaterialTopTabNavigator (at MainTabNavigator.tsx:101)
    in MainTabNavigator (at CompatScreen.tsx:27)
    in ScreenComponent (at createCompatNavigatorFactory.tsx:139)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:85)
    in EnsureSingleNavigator (at SceneView.tsx:84)
    in SceneView (at useDescriptors.tsx:114)
    in SwitchNavigator (at createCompatNavigatorFactory.tsx:153)
    in Navigator (at MainSwitchNavigator.tsx:40)
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
- node_modules\expo\build\environment\muteWarnings.fx.js:27:24 in error
- ... 13 more stack frames from framework internals
```
I guess it's caused that `switchNavigator` still not support React Hooks.
so I think It's better to use stackNavigator instead of switchNavigator.

image

**Comment by hyochan** [comment]
@Ta2Rim Thanks for trying out! I've also tried myself but could not achieve it either. Let's stick to `StackNavigator` for now!

**Comment by hyochan** [comment]
@Ta2Rim I have news for you in my [post](https://medium.com/@dooboolab/react-navigation-v5-%EB%84%A4%EB%B9%84%EA%B2%8C%EC%9D%B4%EC%85%98-%EC%86%8C%EC%8B%9D-%ED%8C%8C%ED%95%B4%EC%B9%98%EA%B8%B0-%EB%B0%8F-%ED%83%80%EC%9E%85%EB%B3%84-%EC%98%88%EC%A0%9C-c8f2919b49e9). The workaround for `SwitchNavigator` is still unreliable.

**Comment by Ta2Rim** [comment]
Thanks! It's very informative.
I wonder what maintainers intended

**Pull request merged**
